name: Build & Deploy

on:
  push:
    branches: [ "prod", "master" ]
  pull_request:
    branches: [ "prod", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ production, development ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set environment-specific variables
        id: set-vars
        run: |
          if [[ "${{ matrix.environment }}" == "production" ]]; then
            echo "APP_NAME=${{ secrets.CAPROVER_PROD_NAME }}" >> $GITHUB_ENV
            echo "APP_TOKEN=${{ secrets.CAPROVER_PROD_TOKEN }}" >> $GITHUB_ENV
          else
            echo "APP_NAME=${{ secrets.CAPROVER_DEV_NAME }}" >> $GITHUB_ENV
            echo "APP_TOKEN=${{ secrets.CAPROVER_DEV_TOKEN }}" >> $GITHUB_ENV
          fi
          echo "CAPROVER_SERVER=${{ secrets.CAPROVER_SERVER }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: "npm"

      - run: npm install

      - run: npm run build

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            dist/
            captain-definition
            Dockerfile
          outPath: deploy.tar

      - run: cat deploy.tar | wc -c

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@main
        with:
          server: ${{ env.CAPROVER_SERVER }}
          app: ${{ env.APP_NAME }}
          token: ${{ env.APP_TOKEN }}
